version: "3"
services:
    frontend:
        image: "quarkus-workshop-ui"
        container_name: "quarkus-ui"
        ports:
            - "3000:80"
        depends_on:
            - fight
    fight:
        image: "quarkus-workshop-fight"
        container_name: "quarkus-fight"
        ports:
            - "8082:8082"
        depends_on:
            - database
            - monitoring
            - hero
            - villain
    hero:
        image: "quarkus-workshop-hero"
        container_name: "quarkus-hero"
        ports:
            - "8083:8083"
        depends_on:
            - database
            - monitoring
    villain:
        image: "quarkus-workshop-villain"
        container_name: "quarkus-villain"
        ports:
            - "8084:8084"
        depends_on:
            - database
            - monitoring
    database:
        image: "postgres:10.5"
        container_name: "super-database"
        ports:
            - "5432:5432"
        volumes:
            - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
    monitoring:
        image: "prom/prometheus"
        container_name: "super-visor"
        ports:
            - 9090:9090
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
